# Generated by Django 5.0.4 on 2024-05-01 19:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestType', models.CharField(choices=[('Time Series', 'Time Series'), ('Heat Map', 'Heat Map'), ('Data Download', 'Data Download')], max_length=15)),
                ('startDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('endDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('temporalLevel', models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=10)),
                ('aggLevel', models.CharField(choices=[('Minimum', 'Minimum'), ('Maximum', 'Maximum'), ('Average', 'Average')], max_length=10)),
                ('north', models.DecimalField(decimal_places=3, max_digits=5)),
                ('east', models.DecimalField(decimal_places=3, max_digits=6)),
                ('south', models.DecimalField(decimal_places=3, max_digits=5)),
                ('west', models.DecimalField(decimal_places=3, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
